version: v1.0
name: build-pipeline
jobs:
- job: First job
  steps:
  - checkout: '{{.cds.workspace}}'
  - script:
    - echo 'foo'
    - mvn package
  - artifactUpload:
      path: target/*.tar.gz
      tag: '{{.cds.version}}'
  requirements:
  - binary: git
